-- Enable pgvector extension
create extension if not exists vector;

-- ── Contacts table ──────────────────────────────────────────────────────────
create table if not exists contacts (
    id bigint generated by default as identity primary key,
    name text not null,
    email text not null,
    message text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Block public access; backend uses service role key to insert
alter table contacts enable row level security;

-- ── Documents table (RAG vector store) ──────────────────────────────────────
create table if not exists documents (
    id bigint generated by default as identity primary key,
    content text,
    metadata jsonb,
    embedding vector(384)  -- 384 dims = Xenova/all-MiniLM-L6-v2
);

-- ── match_documents function (required by LangChain SupabaseVectorStore) ────
create or replace function match_documents (
  query_embedding vector(384),
  match_count int default null,
  filter jsonb default '{}'
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
#variable_conflict use_column
begin
  return query
  select
    id,
    content,
    metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from documents
  where metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
end;
$$;
